hmrc/cgt-calculator-resident-shares-frontend

app/config/CgtErrorHandler.scala, app/config/frontendGlobal.scala, app/connectors/CalculatorConnector.scala, app/controllers/DeductionsController.scala, app/controllers/GainController.scala, app/controllers/IncomeController.scala, app/controllers/ReportController.scala, app/controllers/SaUserController.scala, app/controllers/SummaryController.scala, app/controllers/utils/TimeoutController.scala, app/controllers/utils/package.scala, app/models/CgtExceptions.scala, app/views/warnings/sessionTimeout.scala.html, conf/application.conf, conf/messages, test/config/CgtErrorHandlerSpec.scala, test/controllers/GainControllerSpec/SellForLessActionSpec.scala, test/controllers/utils/RecoverableFutureSpec.scala
DDCNLS-1595: 
- Added implicit class to extend Future[Result] to override Play HttpErrorHandler in order to implement graceful handling of None.get. 
- Added to methods at risk of None.get, added custom Application Exception handling to CalCulatorConnector.
=> Ddcnls 1595

app/config/frontendGlobal.scala, app/config/frontendWiring.scala, app/connectors/CalculatorConnector.scala, app/controllers/DeductionsController.scala, app/controllers/GainController.scala, app/controllers/IncomeController.scala, app/controllers/ReportController.scala, app/controllers/ReviewAnswersController.scala, app/controllers/SaUserController.scala, app/controllers/SummaryController.scala, app/controllers/WhatNextSAController.scala, app/controllers/predicates/ValidActiveSession.scala, app/views/calculation/whatNext/saUser.scala.html, conf/application.conf, project/frontendBuild.scala, test/config/FrontendGlobalSpec.scala, test/connectors/CalculatorConnectorSpec.scala, test/controllers/ReviewAnswersControllerSpec.scala, test/controllers/SummaryActionSpec.scala, test/controllers/helpers/FakeRequestHelper.scala, test/views/calculation/whatNext/SaUserViewSpec.scala
=> Great library upgrade - DL-125

conf/messages, test/assets/MessageLookup.scala
@nehakannaujia - Replace rebasing messaging; unit tests updated.
=> DDCNLS-1863

app/controllers/CgtLanguageController.scala, app/views/calculation/gain/resident_shares_main_template.scala.html, app/views/calculation/resident_main_template.scala.html, conf/app.routes
Changes to language controller and route so that it no longer needs injection. 
This is a test to see if it fixes the issues in QA. 
Dependency change to frontend-bootstrap to follow if this works.
=> DL-1095-c - Changes to injections of language to fix QA

app/controllers/GainController.scala
Changes to gain controller lazy vals added for test in Dev.
=> DL-1095-c - Changes to gain controller addition lazy vals

app/connectors/CalculatorConnector.scala, app/connectors/SessionCacheConnector.scala, app/controllers/DeductionsController.scala, app/controllers/IncomeController.scala, app/controllers/ReportController.scala, app/controllers/ReviewAnswersController.scala, app/controllers/SaUserController.scala, app/controllers/SummaryController.scala, app/controllers/WhatNextNonSaController.scala, app/controllers/WhatNextSAController.scala, app/services/SessionCacheService.scala
Changes to controllers and connectors to have override and lazy vals.
This is for test in the Dev environment.
=> DL-1095- Lazy Val changes for test in Dev

project/MicroService.scala, project/frontendBuild.scala, project/plugins.sbt
Dependency change major and minor.
tests all ran and pass.
=> DL-1095-c - Dependency change to frontend-bootstrap and sbt-autobuild

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, project/MicroService.scala, project/frontendBuild.scala, project/plugins.sbt
Updating cgt-calculator-resident-shares-frontend to new build
=> DL-1242 - Migrating to new build

app/config/ApplicationConfig.scala, app/controllers/FeedbackSurveyController.scala, app/views/calculation/whatNext/whatNextNonSaGain.scala.html, app/views/calculation/whatNext/whatNextSAGain.scala.html, app/views/calculation/whatNext/whatNextSANoGain.scala.html, conf/app.routes, conf/application.conf, conf/messages.cy, conf/messages.en, project/frontendBuild.scala, test/assets/MessageLookup.scala, test/controllers/WhatNextNonSaControllerSpec.scala, test/controllers/WhatNextSaControllerSpec.scala, test/controllers/utils/feedbackSurveyControllerSpec.scala, test/views/calculation/whatNext/WhatNextNonSaGainViewSpec.scala, test/views/calculation/whatNext/WhatNextSAGainViewSpec.scala, test/views/calculation/whatNext/WhatNextSANoGainViewSpec.scala
** Implement Feedback Survey ** 
Implemented feedback survey and test changes.
=> DL-920 Implement feedback survey and test changes

conf/application.conf, project/FrontendBuild.scala, test/views/calculation/gain/DisposalDateViewSpec.scala
**Bug fix** 
Addition of bootstrap filters line in application config along with dependency updates.
=> added play filters for csrf issue + dependency update

app/config/ApplicationConfig.scala, conf/application.conf, project/FrontendBuild.scala, project/plugins.sbt
**New feature**
App config change. Dependency updates.
=> DL-1813: Feedback frontend link change, dependency updates.

conf/application.conf, test/controllers/WhatNextNonSaControllerSpec.scala
=> Update DFS link

app/views/helpers/gainSummaryPartial.scala.html, public/stylesheets/cgt.css
=> DL-2904 - CGT - Accessibility Fixes

build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt
=> DL-3586 - CGT-CALCULATOR-RESIDENT-SHARES-FRONTEND Dependency Updates

conf/application.conf, project/AppDependencies.scala
=> DL-4259 - A11y statement functionality for CGT-RES-SHARES

project/AppDependencies.scala, test/connectors/SessionCacheConnectorSpec.scala
=> DL-4894 - Removed unused dependency and cleared warnings

.bsp/sbt.json, .gitignore, app/common/Dates.scala, app/views/helpers/resident/summaryDateRowHelper.scala.html
=> DL-5109 - CGT: Summary page displays an incorrect year

build.sbt, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt
=> DL-5465 auth-client upgrade

app/views/calculation/gain/worthWhenSoldForLess.scala.html, app/views/playHelpers/formInputMoney.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/WorthWhenSoldForLessActionSpec.scala, test/views/calculation/gain/WorthWhenSoldForLessViewSpec.scala
=> DL-8406 - worth-when-sold-for-less

app/views/calculation/gain/sellForLess.scala.html, app/views/playHelpers/inputRadio.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/SellForLessActionSpec.scala, test/views/calculation/gain/SellForLessViewSpec.scala
=> DL-8405 sellForLess.scala

app/views/calculation/gain/disposalCosts.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/DisposalCostsActionSpec.scala, test/views/calculation/gain/DisposalCostsViewSpec.scala
=> DL-8407 disposalCosts.scala

app/views/calculation/gain/acquisitionValue.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/AcquisitionValueActionSpec.scala, test/views/calculation/gain/AcquisitionValueViewSpec.scala
=> DL-8413 acquisition-value

app/views/calculation/gain/ownerBeforeLegislationStart.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/OwnerBeforeLegislationStartActionSpec.scala, test/views/calculation/gain/OwnerBeforeLegislationStartViewSpec.scala, test/views/helpers/CheckYourAnswersPartialViewSpec.scala
=> DL-8408  owner-before-legislation-start

app/views/calculation/gain/valueBeforeLegislationStart.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/ValueBeforeLegislationStartActionSpec.scala, test/views/calculation/gain/ValueBeforeLegislationStartViewSpec.scala
DL-8409
value-before-legislation-start page UI components updated
=> DL-8409 value-before-legislation-start

app/views/calculation/gain/didYouInheritThem.scala.html, test/controllers/GainControllerSpec/InheritedSharesActionSpec.scala, test/views/calculation/gain/DidYouInheritThemViewSpec.scala
=> DL-8411 - did-you-inherit-them

app/views/calculation/gain/acquisitionCosts.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/AcquisitionCostsActionSpec.scala, test/views/calculation/gain/AcquisitionCostsViewSpec.scala
=> DL-8410 Acquisition Costs

app/views/calculation/gain/worthWhenInherited.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/WorthWhenInheritedActionSpec.scala, test/views/calculation/gain/WorthWhenInheritedViewSpec.scala
=> DL-8412 worth-when-inherited

app/views/calculation/deductions/lossesBroughtForwardValue.scala.html, test/assets/MessageLookup.scala, test/controllers/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala, test/views/calculation/deductions/LossesBroughtForwardValueViewSpec.scala, test/views/helpers/CheckYourAnswersPartialViewSpec.scala
=> DL-8416 losses-brought-forward-value

app/views/calculation/gain/disposalValue.scala.html, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/DisposalValueActionSpec.scala, test/views/calculation/gain/DisposalValueViewSpec.scala
=> DL-8414 disposal-value

app/views/calculation/deductions/lossesBroughtForward.scala.html, app/views/playHelpers/expandableHelpTextHelper.scala.html, conf/messages.cy, conf/messages.en, test/assets/MessageLookup.scala, test/controllers/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala, test/views/calculation/deductions/LossesBroughtForwardViewSpec.scala, test/views/helpers/CheckYourAnswersPartialViewSpec.scala
=> DL-8415 lossesBroughtForward.scala

app/views/calculation/income/personalAllowance.scala.html, test/assets/MessageLookup.scala, test/controllers/IncomeControllerSpec/PersonalAllowanceActionSpec.scala, test/views/calculation/income/PersonalAllowanceViewSpec.scala
=> DL-8418 personal-allowance

app/assets/stylesheets/cgt-calculator-resident-shares.css, app/views/Layout.scala.html, app/views/calculation/checkYourAnswers/checkYourAnswers.scala.html, app/views/playHelpers/checkYourAnswersPartial.scala.html, app/views/playHelpers/resident/summaryDateRowHelper.scala.html, app/views/playHelpers/resident/summaryNumericRowHelper.scala.html, app/views/playHelpers/resident/summaryOptionRowHelper.scala.html, test/assets/MessageLookup.scala, test/controllers/ReviewAnswersControllerSpec.scala, test/views/calculation/checkYourAnswers/CheckYourAnswersViewSpec.scala
=> DL-8419 check-your-answers

app/views/calculation/income/currentIncome.scala.html, test/assets/MessageLookup.scala, test/views/calculation/income/CurrentIncomeViewSpec.scala, test/views/helpers/CheckYourAnswersPartialViewSpec.scala
=> DL-8417 currentIncome.scala

app/views/calculation/summary/deductionsSummary.scala.html, app/views/calculation/summary/finalSummary.scala.html, app/views/calculation/summary/gainSummary.scala.html, app/views/playHelpers/deductionsSummaryPartial.scala.html, app/views/playHelpers/gainSummaryPartial.scala.html, app/views/playHelpers/resident/finalSummaryPartial.scala.html, app/views/playHelpers/resident/summaryNumericRow.scala.html, app/views/playHelpers/resident/summaryNumericRowPartial.scala.html, test/assets/MessageLookup.scala, test/views/calculation/report/SharesDeductionsReportViewSpec.scala, test/views/calculation/report/SharesFinalReportViewSpec.scala, test/views/calculation/report/SharesGainReportViewSpec.scala, test/views/calculation/summary/SharesDeductionsSummaryViewSpec.scala, test/views/calculation/summary/SharesFinalSummaryViewSpec.scala, test/views/calculation/summary/SharesGainSummaryViewSpec.scala
=> DL-8420 3xsummary

app/views/calculation/whatNext/saUser.scala.html, test/assets/MessageLookup.scala, test/controllers/SaUserControllerSpec.scala, test/views/calculation/whatNext/SaUserViewSpec.scala
=> DL-8422 saUser.scala.html

app/views/calculation/whatNext/whatNextNonSaLoss.scala.html, test/assets/MessageLookup.scala, test/views/calculation/whatNext/WhatNextNonSaLossViewSpec.scala
=> DL-8424 what-next-non-sa-loss

app/views/calculation/whatNext/whatNextNonSaGain.scala.html, test/assets/MessageLookup.scala, test/views/calculation/whatNext/WhatNextNonSaGainViewSpec.scala
=> DL-8425 what-next-non-sa-gain

app/views/calculation/whatNext/whatNextSAGain.scala.html, test/assets/MessageLookup.scala, test/controllers/WhatNextSaControllerSpec.scala, test/views/calculation/whatNext/WhatNextSAGainViewSpec.scala
=> DL-8426 what-next-sa-gain

app/views/calculation/whatNext/whatNextSANoGain.scala.html, test/assets/MessageLookup.scala, test/controllers/WhatNextSaControllerSpec.scala, test/views/calculation/whatNext/WhatNextSAFourTimesAEAViewSpec.scala, test/views/calculation/whatNext/WhatNextSANoGainViewSpec.scala
=> DL-8427 what-next-sa-no-gain

app/views/calculation/report/deductionsSummaryReport.scala.html, app/views/calculation/report/finalSummaryReport.scala.html, app/views/calculation/report/gainSummaryReport.scala.html, test/assets/MessageLookup.scala, test/views/calculation/report/SharesDeductionsReportViewSpec.scala, test/views/calculation/report/SharesFinalReportViewSpec.scala, test/views/calculation/report/SharesGainReportViewSpec.scala
=> DL-8421 - 3 X report

app/views/calculation/whatNext/whatNextSAFourTimesAEA.scala.html, test/assets/MessageLookup.scala, test/controllers/WhatNextSaControllerSpec.scala, test/views/calculation/whatNext/WhatNextSAFourTimesAEAViewSpec.scala, test/views/calculation/whatNext/WhatNextSANoGainViewSpec.scala
=> DL-8423 whatNextSANoGain.scala

conf/messages.cy, conf/messages.en, test/assets/MessageLookup.scala, test/views/calculation/gain/DisposalDateViewSpec.scala
=> DL-8559 - updated date hint and error

app/controllers/DeductionsController.scala, app/controllers/IncomeController.scala, app/controllers/SummaryController.scala, app/models/resident/TaxYearModel.scala, app/views/calculation/deductions/lossesBroughtForward.scala.html, app/views/calculation/deductions/lossesBroughtForwardValue.scala.html, app/views/calculation/income/currentIncome.scala.html, app/views/calculation/income/personalAllowance.scala.html, app/views/calculation/summary/deductionsSummary.scala.html, app/views/calculation/summary/finalSummary.scala.html, app/views/calculation/summary/gainSummary.scala.html, app/views/playHelpers/checkYourAnswersPartial.scala.html, app/views/playHelpers/deductionsSummaryPartial.scala.html, app/views/playHelpers/gainSummaryPartial.scala.html, app/views/playHelpers/resident/finalSummaryPartial.scala.html, conf/messages.cy, conf/messages.en, test/controllers/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala, test/controllers/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala, test/controllers/IncomeControllerSpec/CurrentIncomeActionSpec.scala, test/controllers/IncomeControllerSpec/PersonalAllowanceActionSpec.scala, test/views/calculation/deductions/LossesBroughtForwardValueViewSpec.scala, test/views/calculation/deductions/LossesBroughtForwardViewSpec.scala, test/views/calculation/income/CurrentIncomeViewSpec.scala, test/views/calculation/income/PersonalAllowanceViewSpec.scala, test/views/calculation/summary/SharesDeductionsSummaryViewSpec.scala, test/views/calculation/summary/SharesFinalSummaryViewSpec.scala, test/views/calculation/summary/SharesGainSummaryViewSpec.scala
=> DL-8555 removed slashes from tax years

app/views/calculation/whatNext/whatNextSAFourTimesAEA.scala.html, conf/messages.cy, conf/messages.en, test/assets/MessageLookup.scala
=> DL-8558 'Your Options' content change

conf/messages.cy
=> DL-8554 fixed failing test

app/views/calculation/gain/acquisitionCosts.scala.html, app/views/calculation/gain/disposalCosts.scala.html, app/views/calculation/gain/valueBeforeLegislationStart.scala.html, app/views/calculation/gain/worthWhenInherited.scala.html, test/views/calculation/gain/AcquisitionCostsViewSpec.scala, test/views/calculation/gain/DisposalCostsViewSpec.scala, test/views/calculation/gain/ValueBeforeLegislationStartViewSpec.scala, test/views/calculation/gain/WorthWhenInheritedViewSpec.scala
=> DL-8904 changes from hint-text to body-text

conf/messages.cy, conf/messages.en, test/assets/MessageLookup.scala
=> DL-8905 removed apostrophes

build.sbt
=> DL-10008 Removed targetJvm

README.md
=> DL-9879 Update README.md

app/connectors/CalculatorConnector.scala, app/connectors/SessionCacheConnector.scala, app/services/SessionCacheService.scala, conf/application.conf, test/common/CommonPlaySpec.scala, test/common/WithCommonFakeApplication.scala, test/controllers/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala, test/controllers/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala, test/controllers/GainControllerSpec/AcquisitionCostsActionSpec.scala, test/controllers/GainControllerSpec/AcquisitionValueActionSpec.scala, test/controllers/GainControllerSpec/DisposalCostsActionSpec.scala, test/controllers/GainControllerSpec/DisposalDateActionSpec.scala, test/controllers/GainControllerSpec/DisposalValueActionSpec.scala, test/controllers/GainControllerSpec/InheritedSharesActionSpec.scala, test/controllers/GainControllerSpec/OutsideTaxYearsActionSpec.scala, test/controllers/GainControllerSpec/OwnerBeforeLegislationStartActionSpec.scala, test/controllers/GainControllerSpec/SellForLessActionSpec.scala, test/controllers/GainControllerSpec/ValueBeforeLegislationStartActionSpec.scala, test/controllers/GainControllerSpec/WorthWhenInheritedActionSpec.scala, test/controllers/GainControllerSpec/WorthWhenSoldForLessActionSpec.scala, test/controllers/IncomeControllerSpec/CurrentIncomeActionSpec.scala, test/controllers/IncomeControllerSpec/PersonalAllowanceActionSpec.scala, test/controllers/ReviewAnswersControllerSpec.scala, test/controllers/SaUserControllerSpec.scala, test/controllers/SummaryActionSpec.scala, test/controllers/WhatNextNonSaControllerSpec.scala, test/controllers/WhatNextSaControllerSpec.scala, test/controllers/utils/RecoverableFutureSpec.scala, test/controllers/utils/TimeoutControllerSpec.scala, test/services/SessionCacheServiceSpec.scala
=> DL-11436 - removed implicit ExecutionContext

app/controllers/GainController.scala
=> DL-11569 link error msg to input field

app/controllers/utils/package.scala, app/views/playHelpers/moneyInputFormat.scala.html, app/views/playHelpers/resident/summaryNumericHelpTextHelper.scala.html, app/views/playHelpers/resident/summaryNumericRowHelper.scala.html, app/views/playHelpers/resident/summaryNumericRowPartial.scala.html
=> DL-11581 remove form-hint class from spans

conf/application.conf, project/AppDependencies.scala, test/views/calculation/summary/SharesGainSummaryViewSpec.scala
=> DL-11782 remove csp directive

app/config/ApplicationConfig.scala, app/views/Layout.scala.html, conf/application.conf
=> DL-11944 Convert layout to use hmrcStandardPage

app/connectors/CalculatorConnector.scala, app/views/playHelpers/deductionsSummaryPartial.scala.html, app/views/playHelpers/gainSummaryPartial.scala.html, app/views/playHelpers/resident/finalSummaryPartial.scala.html, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/connectors/CalculatorConnectorSpec.scala
=> DL-11991 Removing joda time

app/views/calculation/report/deductionsSummaryReport.scala.html, app/views/calculation/report/finalSummaryReport.scala.html, app/views/calculation/report/gainSummaryReport.scala.html, app/views/calculation/summary/deductionsSummary.scala.html, app/views/calculation/summary/finalSummary.scala.html, app/views/calculation/summary/gainSummary.scala.html, test/assets/MessageLookup.scala, test/controllers/SummaryActionSpec.scala, test/views/calculation/report/SharesDeductionsReportViewSpec.scala, test/views/calculation/report/SharesFinalReportViewSpec.scala, test/views/calculation/report/SharesGainReportViewSpec.scala, test/views/calculation/summary/SharesDeductionsSummaryViewSpec.scala, test/views/calculation/summary/SharesFinalSummaryViewSpec.scala, test/views/calculation/summary/SharesGainSummaryViewSpec.scala
=> DL-11580 updated summary titles

app/views/calculation/outsideTaxYear.scala.html, app/views/calculation/whatNext/whatNextNonSaGain.scala.html, app/views/calculation/whatNext/whatNextSAGain.scala.html
=> [DLS-9448] added button role

app/views/playHelpers/resident/finalSummaryPartial.scala.html, test/views/calculation/summary/SharesFinalSummaryViewSpec.scala, test/views/helpers/FinalSummaryPartialViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/DLS-9697
=> DLS-9697 fix duplicate ids

app/views/playHelpers/resident/finalSummaryPartial.scala.html, test/views/calculation/summary/SharesFinalSummaryViewSpec.scala, test/views/helpers/FinalSummaryPartialViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/DLS-9456
=> DLS-9456 Fix CYA heading

app/views/calculation/deductions/lossesBroughtForwardValue.scala.html, app/views/calculation/gain/acquisitionCosts.scala.html, app/views/calculation/gain/acquisitionValue.scala.html, app/views/calculation/gain/disposalCosts.scala.html, app/views/calculation/gain/disposalValue.scala.html, app/views/calculation/gain/valueBeforeLegislationStart.scala.html, app/views/calculation/gain/worthWhenInherited.scala.html, app/views/calculation/gain/worthWhenSoldForLess.scala.html, app/views/calculation/income/currentIncome.scala.html, app/views/calculation/income/personalAllowance.scala.html, app/views/playHelpers/formInputMoney.scala.html, conf/messages.cy, conf/messages.en, project/AppDependencies.scala, project/plugins.sbt, test/assets/MessageLookup.scala, test/controllers/utils/RecoverableFutureSpec.scala, test/views/calculation/deductions/LossesBroughtForwardValueViewSpec.scala, test/views/calculation/gain/AcquisitionCostsViewSpec.scala, test/views/calculation/gain/AcquisitionValueViewSpec.scala, test/views/calculation/gain/DisposalCostsViewSpec.scala, test/views/calculation/gain/DisposalValueViewSpec.scala, test/views/calculation/gain/ValueBeforeLegislationStartViewSpec.scala, test/views/calculation/gain/WorthWhenSoldForLessViewSpec.scala, test/views/calculation/income/CurrentIncomeViewSpec.scala
=> DLS-9859 - CGT Calc Res Shares Currency hints fixes

project/AppDependencies.scala
**Maintenance**
Compliance with GDS requirements to update the front end library version to the latest which provides the new Tudor Crown logo.
=> [DLS-10009] Tudor Crown update

conf/messages.cy, conf/messages.en, test/assets/MessageLookup.scala, test/controllers/GainControllerSpec/SellForLessActionSpec.scala, test/views/calculation/deductions/LossesBroughtForwardValueViewSpec.scala, test/views/calculation/deductions/LossesBroughtForwardViewSpec.scala, test/views/calculation/summary/SharesFinalSummaryViewSpec.scala
ran ATs (due to content change) and they pass
ran Unit tests - all pass
=> DLS-9896 - addressed outdated government gateway messages

app/assets/stylesheets/cgt-calculator-resident-shares.css, app/views/calculation/checkYourAnswers/checkYourAnswers.scala.html, app/views/playHelpers/checkYourAnswersPartial.scala.html, app/views/playHelpers/resident/summaryDateRowHelper.scala.html, app/views/playHelpers/resident/summaryNumericRowHelper.scala.html, app/views/playHelpers/resident/summaryOptionRowHelper.scala.html
https://jira.tools.tax.service.gov.uk/browse/DLS-9455
=> DLS-9455 CYA layout

app/connectors/CalculatorConnector.scala, app/constructors/CalculateRequestConstructor.scala, conf/application.conf, test/constructors/CalculateRequestConstructorSpec.scala
thank you Mahesh and Jonathan!
=> DLS-10998: V2 upgrade uri interpolation fix

project/AppDependencies.scala, project/plugins.sbt
Update to the AppDependencies & plugins.sbt
=> DLS-10860/Hugo/updateService
